version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8080:80"
        depends_on:
            - app
        container_name: milani_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: milani_app

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8101:3306"
        command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        container_name: milani_mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=300M
            - MAX_EXECUTION_TIME=1000
            - MEMORY_LIMIT=1G
        container_name: milani_phpmyadmin
